import 'package:flutter/material.dart';

abstract class Constants {
  static const primaryColor = Color(0xFF35C3B3);

  static const regions = [
    'Banskobystrický kraj',
    'Bratislavský kraj',
    'Košický kraj',
    'Nitrianský kraj',
    'Prešovský kraj',
    'Trenčianský kraj',
    'Trnavský kraj',
  ];
  static const districts = [
    'Bánovce nad Bebravou',
    'Banská Bystrica',
    'Banská Štiavnica',
    'Bardejov',
    'Bratislava I',
    'Bratislava II',
    'Bratislava III',
    'Bratislava IV',
    'Bratislava V',
    'Brezno',
    'Bytča',
    'Čadca',
    'Detva',
    'Dolný Kubín',
    'Dunajská Streda',
    'Galanta',
    'Gelnica',
    'Hlohovec',
    'Humenné',
    'Ilava',
    'Kežmarok',
    'Komárno',
    'Košice I',
    'Košice II',
    'Košice III',
    'Košice IV',
    'Košice-okolie',
    'Krupina',
    'Kysucké Nové Mesto',
    'Levice',
    'Levoča',
    'Liptovský Mikuláš',
    'Lučenec',
    'Malacky',
    'Martin',
    'Medzilaborce',
    'Michalovce',
    'Myjava',
    'Námestovo',
    'Nitra',
    'Nové Mesto nad Váhom',
    'Nové Zámky',
    'Partizánske',
    'Pezinok',
    'Piešťany',
    'Poltár',
    'Poprad',
    'Považská Bystrica',
    'Prešov',
    'Prievidza',
    'Púchov',
    'Revúca',
    'Rimavská Sobota',
    'Rožňava',
    'Ružomberok',
    'Sabinov',
    'Senec',
    'Senica',
    'Skalica',
    'Snina',
    'Sobrance',
    'Spišská Nová Ves',
    'Stará Ľubovňa',
    'Stropkov',
    'Svidník',
    'Šaľa',
    'Topoľčany',
    'Trebišov',
    'Trenčín',
    'Trnava',
    'Turčianske Teplice',
    'Tvrdošín',
    'Veľký Krtíš',
    'Vranov nad Topľou',
    'Zlaté Moravce',
    'Zvolen',
    'Žarnovica',
    'Žiar nad Hronom',
    'Žilina',
  ];
  static const genders = ['Ženy', 'Muži'];
  static const ages = [
    'Od 18 do 26 rokov',
    'Od 27 do 50 rokov',
    'Nad 51 rokov',
  ];
  static const types = ['Domov na pol ceste', 'Nocľaháreň', 'Útulok'];
}
